export const DISHES_REQUEST = 'DISHES_REQUEST';
export const DISHES_SUCCESS = 'DISHES_SUCCESS';
export const DISHES_ERROR = 'DISHES_ERROR';

export const GET_DISHES_SUCCESS = 'GET_DISHES_SUCCESS';

export const ORDERS_REQUEST = 'ORDERS_REQUEST';
export const ORDERS_SUCCESS = 'ORDERS_SUCCESS';
export const ORDERS_ERROR = 'ORDERS_FAILURE';

export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';